version: '3.7'

services:
  admin:
    container_name: adminAppCon
    expose:
      - "1339"
    ports:
      - "localhost:1339:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart:
      "always"